name: Deploy Backend to Azure

on:
  push:
    branches: [master]
    paths:
      - 'backend/**'
      - '.github/workflows/azure-backend.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ai-analytics-backend-2025-d7hufxd3bmhnfmf8
  AZURE_WEBAPP_PACKAGE_PATH: './backend'
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          export DJANGO_SETTINGS_MODULE=data_analysis_api.settings_prod
          python manage.py collectstatic --noinput

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
            !${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ./backend

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./backend
          startup-command: 'python manage.py collectstatic --noinput && python manage.py migrate && gunicorn data_analysis_api.wsgi:application --bind 0.0.0.0:8000'
